exp: bert4rec-bert
model: bert
mode: train
freeze_emb: false
tasks:
  -
    name: bert4rec
    params:
      known_items: k_global
      pred_items: p_global
      mask_last_ratio: 0.1
    injection: true
load:
  load_ckpt: null
  load_model_only: true
  relax_load: false
store:
  interval: 10
  super_store: true
  monitor: a.loss < b.loss
policy:
  use_sep_token: true
  pin_memory: false
  epoch: 100
  epoch_start: 0
  lr: 0.01
  batch_size: 64
  accumulate_batch: 4
  device: gpu
  n_warmup: 600
  check_interval: -2
