exp: curriculum-bert-double-step-5
model: bert
mode: train
freeze_emb: false
tasks:
  -
    name: cu-cluster-mlm
    params:
      weighted: false
      weight_decay: 1
      curriculum_steps: 1
      cluster_json: clusters/cluster_vocab.json
      grad_cluster_loss: true
      grad_local_loss: true

load:
  load_ckpt: curriculum-bert-double-step-5/epoch_99.bin
#  load_ckpt: null
  load_model_only: true
  relax_load: false
policy:
  pin_memory: false
  epoch: 100
  epoch_start: 100
  lr: 0.01
  batch_size: 256
  accumulate_batch: 1
  device: gpu
  n_warmup: 600
  check_interval: -2
  store_interval: 5
