exp: curriculum-bart-double-weight-two-stage
model: bart
mode: train
freeze_emb: false
tasks:
  -
    name: cu-cluster-mlm-bart
    params:
      weighted: true
      weight_decay: 1.0
      curriculum_steps: 20
      cluster_json: clusters/cluster_vocab.json
      grad_cluster_loss: true
      grad_local_loss: false
load:
  load_ckpt: null
  load_model_only: true
  relax_load: false
store:
  interval: 10
  super_store: true
  monitor: a.cluster_loss < b.cluster_loss
  task: null
  top: null
policy:
  pin_memory: false
  epoch: 100
  epoch_start: 0
  lr: 0.01
  batch_size: 64
  accumulate_batch: 4
  device: gpu
  n_warmup: 600
  check_interval: -2
