exp: curriculum-mlm-bert
model: bert
mode: train
freeze_emb: false
tasks:
  -
    name: cu-mlm
    params:
      weighted: false
      weight_decay: 1
      curriculum_steps: 20
      known_items: k_cluster
      pred_items: p_cluster

load:
  load_ckpt: curriculum-mlm-bert/epoch_99.bin
  load_model_only: true
  relax_load: false
policy:
  pin_memory: false
  epoch: 100
  epoch_start: 100
  lr: 0.0005
  batch_size: 64
  accumulate_batch: 16
  device: gpu
  n_warmup: 0
  check_interval: -10
  store_interval: 5
