exp: curriculum-mlm-bart
model: bart
mode: train
freeze_emb: false
tasks:
  -
    name: en-mlm
  -
    name: de-cu-mlm
    params:
      weighted: true
      weight_decay: 1

load:
  load_ckpt: null
  load_model_only: true
  relax_load: false
policy:
  use_sep_token: true
  pin_memory: false
  epoch: 100
  epoch_start: 0
  lr: 0.0002
  batch_size: 64
  accumulate_batch: 16
  device: gpu
  n_warmup: 0
  check_interval: -10
  store_interval: 5
