exp: curriculum-mlm-bert
model: bert
mode: train
freeze_emb: false
tasks:
  -
    name: cu-mlm
    params:
      weighted: false
      weight_decay: 1
      curriculum_steps: 20

load:
  load_ckpt: null
  load_model_only: true
  relax_load: false
policy:
  use_sep_token: true
  pin_memory: false
  epoch: 100
  epoch_start: 0
  lr: 0.0005
  batch_size: 64
  accumulate_batch: 16
  device: gpu
  n_warmup: 600
  check_interval: -10
  store_interval: 5
