exp: naive-mlm-uni
model: bart
mode: train
freeze_emb: false
tasks:
  -
    name: en-mlm
  -
    name: de-mlm
    params:
      curriculum_steps: 1
load:
  load_ckpt: null
  load_model_only: true
  relax_load: false
policy:
  use_sep_token: true
  pin_memory: true
  epoch: 50
  epoch_start: 0
  lr: 0.0001
  batch_size: 64
  accumulate_batch: 16
  device: gpu
  n_warmup: 0
  check_interval: -10
  store_interval: 5
