exp: test-curriculum-bert-double-step
mode: test__curriculum
model: bert
freeze_emb: false
tasks:
  -
    name: cu-cluster-mlm
    params:
      weighted: false
      curriculum_steps: 20
      weight_decay: 1
      cluster_json: clusters/cluster_vocab.json
load:
  load_ckpt: null
  load_model_only: false
  relax_load: false
  super_load: true
  ckpt_base_path: curriculum-bert-double-step-5
#  epochs: "map(lambda x: 5 * x + 54, list(range(10)))"
  epochs: "[84, 89, 94, 99]"
#  epochs:
#    interval: 5
#    until: 100
#    start: 0
#  wait_load: true
policy:
  pin_memory: false
  batch_size: 256
  device: gpu
  n_metrics: [5, 10]
