exp: test-curriculum-bart-double-time
mode: test__curriculum_time
model: bart
freeze_emb: false
tasks:
  - name: en-cluster-mlm
    params:
      cluster_json: clusters/cluster_vocab.json
      grad_cluster_loss: true
      grad_local_loss: true
    only_initialization: true
  -
    name: de-cu-cluster-mlm
    params:
      weighted: true
      weight_decay: 1.0
      curriculum_steps: 20
      cluster_json: clusters/cluster_vocab.json
      grad_cluster_loss: true
      grad_local_loss: true
load:
  load_ckpt: null
  load_model_only: false
  relax_load: false
  super_load: false
policy:
  pin_memory: false
  batch_size: 1
  device: gpu
  n_metrics: [5, 10]
