exp: test-curriculum-bert-single-time
mode: test__curriculum_time
model: bert
freeze_emb: false
tasks:
  -
    name: cu-mlm
    params:
      weighted: false
      weight_decay: 1
      curriculum_steps: 1
      known_items: k_global
      pred_items: p_global

load:
  load_ckpt: null
  load_model_only: false
  relax_load: false
  super_load: false
policy:
  pin_memory: false
  batch_size: 1
  device: gpu
  n_metrics: [5, 10]
