exp: test-curriculum
mode: test__curriculum
model: bert
freeze_emb: false
tasks:
  -
    name: cu-cluster-mlm
    params:
      weighted: false
      curriculum_steps: 1
      weight_decay: 1
      cluster_json: clusters/cluster_vocab.json
load:
  load_ckpt: null
  load_model_only: false
  relax_load: false
  super_load: true
  ckpt_base_path: curriculum-mlm-bert-cluster
#  epochs: "map(lambda x: 5 * x + 4, list(range(6)))"
  epochs: "[4]"
policy:
  pin_memory: false
  batch_size: 256
  device: gpu
  n_metrics: [10, 30, 50]
