exp: test-bert4rec
mode: test__left2right
model: bert
freeze_emb: false
tasks:
  -
    name: bert4rec
    params:
      known_items: known_items
      pred_items: pred_items
      mask_last_ratio: 0.1
load:
  load_ckpt: null
  load_model_only: false
  relax_load: false
  super_load: true
  ckpt_base_path: bert4rec-bert
  epochs: "map(lambda x: 5 * x + 4, list(range(2)))"
policy:
  use_sep_token: true
  pin_memory: true
  batch_size: 64
  device: gpu
  n_metrics: [10, 30, 50]
