exp: test-curriculum
mode: test__curriculum
model: bart
freeze_emb: false
tasks:
  -
    name: en-mlm
    only_initialization: true
  -
    name: de-cu-mlm
    params:
      weighted: true
      weight_decay: 1
load:
  load_ckpt: null
  load_model_only: false
  relax_load: false
  super_load: true
  ckpt_base_path: curriculum-mlm-bart
  epochs: "map(lambda x: 5 * x + 4, list(range(2)))"
policy:
  use_sep_token: true
  pin_memory: true
  batch_size: 64
  device: gpu
  n_metrics: [10, 30, 50]
