exp: test-naive
mode: test
freeze_emb: false
tasks:
  -
    name: mlm
    params:
      curriculum_steps: 1
      epoch_ratio: 1
      uni_mask: true
load:
  load_ckpt: null
  load_model_only: false
  relax_load: false
  super_load: true
  ckpt_base_path: naive-mlm
  epochs: "map(lambda x: 2 * x + 1, list(range(25)))"
policy:
  add_sep_token: true
  pin_memory: true
  batch_size: 64
  device: gpu
  hit_rates: [10, 50, 100]
