exp: test-curriculum
mode: test__curriculum
model: bert
freeze_emb: false
tasks:
  -
    name: cu-mlm
    params:
      weighted: true
      weight_decay: 1
load:
  load_ckpt: null
  load_model_only: false
  relax_load: false
  super_load: true
  ckpt_base_path: curriculum-mlm-bert
#  epochs: "[99]"
  epochs: "map(lambda x: 5 * x + 4, list(range(6)))"
policy:
  pin_memory: false
  batch_size: 256
  device: gpu
  n_metrics: [10, 30, 50]
