exp: test-curriculum-bart-double-weight
mode: test__curriculum
model: bart
freeze_emb: false
tasks:
  -
    name: cu-cluster-mlm-bart
    params:
      weighted: true
      weight_decay: 1.0
      curriculum_steps: 20
      cluster_json: clusters/cluster_vocab.json
      grad_cluster_loss: true
      grad_local_loss: true
load:
  load_ckpt: null
  load_model_only: false
  relax_load: false
  super_load: true
  ckpt_base_path: curriculum-bart-double-weight
  auto_load: true
#  epochs: "map(lambda x: 5 * x + 54, list(range(10)))"
#  epochs: "[24, 49, 89, 94]"
  epochs:
    interval: 10
    until: 200
    start: 0
  wait_load: true
policy:
  pin_memory: false
  batch_size: 256
  device: gpu
  n_metrics: [5, 10]
