dataset: zhihu-n10
store:
  data_dir: data/ListContUni/{config.dataset}
  save_dir: saving/{config.dataset}/{exp.model}-{config.model_config.encoder_layers}L{config.model_config.encoder_attention_heads}H/
data:
  split:
    train:
      weight: 8
    dev:
      weight: 1
    test:
      weight: 1
  shuffle: true
  filter:
    p_local:
      - len(x) >= 5
set:
  encoder_order:
    - [k_cluster, k_global, k_local]
  decoder_order:
    - [p_cluster, p_global, p_local]
  append:
    - index
  use_sep_token: true
  use_cls_token: false
model_config:
  encoder_layers: 1
  decoder_layers: 1
  encoder_attention_heads: 4
  decoder_attention_heads: 4
  hidden_size: 64
