dataset: zhihu
store:
  data_dir: data/ListContUni/{dataset}
  save_dir: saving/{dataset}/{model}-E{hidden_size}/
data:
  split:
    train:
      weight: 8
    dev:
      weight: 1
    test:
      weight: 1
  shuffle: true
  filter:
    pred_items:
      - len(x) >= 5
set:
  encoder_order:
    - known_items
  decoder_order:
    - pred_items
  append:
    - list_id
    - user_id
    - index
model_config:
  encoder_layers: 3
  decoder_layers: 3
  encoder_attention_heads: 8
  decoder_attention_heads: 8
  hidden_size: 64
