dataset: zhihu
store:
  data_dir: data/ListContUni/{dataset}
  save_dir: saving/{dataset}/{model}-E{hidden_size}/
data:
  split:
    train:
      weight: 8
    dev:
      weight: 1
    test:
      weight: 1
  shuffle: true
  filter:
    pred_items:
      - len(x) >= 5
set:
  order:
    - known_items
    - pred_items
  append:
    - list_id
    - user_id
    - index
  use_sep_token: true
  use_cls_token: true
model_config:
  hidden_size: 64
  num_hidden_layers: 3
  num_attention_heads: 8
