dataset: zhihu-n100
store:
  data_dir: data/ListContUni/{dataset}
  save_dir: saving/{dataset}/{model}-E{hidden_size}/
data:
  split:
    train:
      weight: 8
    dev:
      weight: 1
    test:
      weight: 1
  shuffle: true
  filter:
    p_cluster:
      - len(x) >= 5
set:
  order:
    - [k_cluster, k_global]
    - [p_cluster, p_global]
  append:
    - index
  use_sep_token: true
  use_cls_token: true
model_config:
  hidden_size: 64
  num_hidden_layers: 3
  num_attention_heads: 8
